[toolchain]

[features]
seeds = true
resolution = true
skip-lint = false

[programs.localnet]
calculator = "49vtggxyFGy6nZchtsDcpGcUNz5mxAE4P7DozgRnKEKH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
